
---
- name: OS Path chooser (Linux Success - Windwos Fail)
  hosts: "{{ target_hosts }}"
  vars:
    target_hosts: "{{ vm_name if vm_name is defined else 'all' | default('all') }}"
  gather_facts: false
  tasks:
- name: Setting Stats for the CI 
  ansible.builtin.set_stats:
    data:
      new_vm_name: "{{ vm_name }}"
      new_vm_os: "{{ virtualmachine_ostype_choice if (virtualmachine_ostype_choice is defined and virtualmachine_ostype_choice != '') else 'Linux' | default ('Linux') }}"
      new_vm_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      new_vm_provisioner: Ansible
      #for SNOW Workflows
      ci_name: "{{ vm_name }}"
      ci_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      ci_os: "{{ virtualmachine_ostype_choice if (virtualmachine_ostype_choice is defined and virtualmachine_ostype_choice != '') else 'Linux' | default ('Linux') }}"
      ci_provisioner: "{{ new_vm_provisioner | default('Ansible') }}"
      ci_manufacturer: "{{ new_vm_platform | default('VMWare') }}"







